BEGIN TRANSACTION;
DROP TABLE IF EXISTS "nromalización";
CREATE TABLE "nromalización" (
	"field1"	TEXT,
	"field2"	TEXT,
	"field3"	TEXT
);
INSERT INTO "nromalización" VALUES ('--',NULL,NULL);
INSERT INTO "nromalización" VALUES ('-- Archivo generado con SQLiteStudio v3.4.4 el dom. sept. 1 12:53:32 2024',NULL,NULL);
INSERT INTO "nromalización" VALUES ('--',NULL,NULL);
INSERT INTO "nromalización" VALUES ('-- Codificación de texto usada: UTF-8',NULL,NULL);
INSERT INTO "nromalización" VALUES ('--',NULL,NULL);
INSERT INTO "nromalización" VALUES ('PRAGMA foreign_keys = off;',NULL,NULL);
INSERT INTO "nromalización" VALUES ('BEGIN TRANSACTION;',NULL,NULL);
INSERT INTO "nromalización" VALUES (NULL,NULL,NULL);
INSERT INTO "nromalización" VALUES ('-- Tabla: alumno',NULL,NULL);
INSERT INTO "nromalización" VALUES ('CREATE TABLE IF NOT EXISTS alumno (matricula INTEGER REFERENCES id_student (matricula) NOT NULL','nro de materia INTEGER NOT NULL REFERENCES materia (nro de materia));',NULL);
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (4','126);');
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (5','124);');
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (9','125);');
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (6','128);');
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (8','127);');
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (7','129);');
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (10','124);');
INSERT INTO "nromalización" VALUES ('INSERT INTO alumno (matricula','nro de materia) VALUES (4','128);');
INSERT INTO "nromalización" VALUES (NULL,NULL,NULL);
INSERT INTO "nromalización" VALUES ('-- Tabla: carrera',NULL,NULL);
INSERT INTO "nromalización" VALUES ('CREATE TABLE IF NOT EXISTS carrera (nro de carrera INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT','carrera TEXT NOT NULL);',NULL);
INSERT INTO "nromalización" VALUES ('INSERT INTO carrera (nro de carrera','carrera) VALUES (2','''electricidad'');');
INSERT INTO "nromalización" VALUES ('INSERT INTO carrera (nro de carrera','carrera) VALUES (3','''sistemas'');');
INSERT INTO "nromalización" VALUES ('INSERT INTO carrera (nro de carrera','carrera) VALUES (4','''dibujo técnico'');');
INSERT INTO "nromalización" VALUES ('INSERT INTO carrera (nro de carrera','carrera) VALUES (5','''contabilidad'');');
INSERT INTO "nromalización" VALUES ('INSERT INTO carrera (nro de carrera','carrera) VALUES (6','''metalisteria'');');
INSERT INTO "nromalización" VALUES ('INSERT INTO carrera (nro de carrera','carrera) VALUES (7','''quimica'');');
INSERT INTO "nromalización" VALUES (NULL,NULL,NULL);
INSERT INTO "nromalización" VALUES ('-- Tabla: id_student',NULL,NULL);
INSERT INTO "nromalización" VALUES ('CREATE TABLE IF NOT EXISTS id_student (matricula INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL','nombre TEXT NOT NULL','telefono NUMERIC NOT NULL');
INSERT INTO "nromalización" VALUES ('INSERT INTO id_student (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO id_student (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO id_student (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO id_student (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO id_student (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO id_student (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO id_student (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES (NULL,NULL,NULL);
INSERT INTO "nromalización" VALUES ('-- Tabla: materia',NULL,NULL);
INSERT INTO "nromalización" VALUES ('CREATE TABLE IF NOT EXISTS materia (materia TEXT NOT NULL','nro de materia INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT);',NULL);
INSERT INTO "nromalización" VALUES ('INSERT INTO materia (materia','nro de materia) VALUES (''Bases de datos''','124);');
INSERT INTO "nromalización" VALUES ('INSERT INTO materia (materia','nro de materia) VALUES (''Planos de corriente''','125);');
INSERT INTO "nromalización" VALUES ('INSERT INTO materia (materia','nro de materia) VALUES (''Dibujo digital''','126);');
INSERT INTO "nromalización" VALUES ('INSERT INTO materia (materia','nro de materia) VALUES (''tabla de costos''','127);');
INSERT INTO "nromalización" VALUES ('INSERT INTO materia (materia','nro de materia) VALUES (''Quimica Organica''','128);');
INSERT INTO "nromalización" VALUES ('INSERT INTO materia (materia','nro de materia) VALUES (''Soldadura''','129);');
INSERT INTO "nromalización" VALUES (NULL,NULL,NULL);
INSERT INTO "nromalización" VALUES ('-- Tabla: unidos',NULL,NULL);
INSERT INTO "nromalización" VALUES ('CREATE TABLE IF NOT EXISTS unidos (matricula INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL','nombre TEXT NOT NULL','telefono NUMERIC NOT NULL');
INSERT INTO "nromalización" VALUES ('INSERT INTO unidos (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO unidos (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO unidos (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO unidos (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO unidos (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO unidos (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES ('INSERT INTO unidos (matricula','nombre','telefono');
INSERT INTO "nromalización" VALUES (NULL,NULL,NULL);
INSERT INTO "nromalización" VALUES ('COMMIT TRANSACTION;',NULL,NULL);
INSERT INTO "nromalización" VALUES ('PRAGMA foreign_keys = on;',NULL,NULL);
COMMIT;
